# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

fyber: &fyber
  appid: 157
  format: 'json'
  device_id: '2b6f0cc904d137be2e1730235f5664094b831186'
  locale: 'de'
  ip: '109.235.143.113'
  offer_types: 112
  api_key: 'b07a12df7d52e6c118e5d47d3f9e60135b109a1f'
  api_host: 'http://api.sponsorpay.com/feed/v1/'

development:
  secret_key_base: 372d930f709bf3c7736483b15702fdbe275aaee4c431866a895a38f0ad8097729b9cbecef1d4e093151594c9daf4cbfd7fc81caf3dfc6eef4c5eee5cdbf20653
  fyber:
    <<: *fyber


test:
  secret_key_base: 19bf9e9fb882890f527ef76b5468b9e236ccc712c0f7ac42f29f08140f6f76542785f0a7846795d8464a65e5652e31db7838bb170bce688be3669636f91c127a
  fyber:
    <<: *fyber

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  fyber:
    <<: *fyber
